/************************************************************************\
© 2024-2025 Denis Brunet, University of Geneva, Switzerland.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
\************************************************************************/

#pragma     hdrstop
//-=-=-=-=-=-=-=-=-

#include    "Volumes.AAL.h"

namespace crtl {

//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
/*                                        // Storing Cartool version of the AAL1 ROI names, joining the old and new format
const TAALRoi   AAL1Codes[ NumAAL1Codes ] =
                        {
                        {   1,  "FAG",          "Precentral_L",         2001 },
                        {   2,  "FAD",          "Precentral_R",         2002 },
                        {   3,  "F1G",          "Frontal_Sup_L",        2101 },
                        {   4,  "F1D",          "Frontal_Sup_R",        2102 },
                        {   5,  "F1OG",         "Frontal_Sup_Orb_L",    2111 },
                        {   6,  "F1OD",         "Frontal_Sup_Orb_R",    2112 },
                        {   7,  "F2G",          "Frontal_Mid_L",        2201 },
                        {   8,  "F2D",          "Frontal_Mid_R",        2202 },
                        {   9,  "F2OG",         "Frontal_Mid_Orb_L",    2211 },
                        {  10,  "F2OD",         "Frontal_Mid_Orb_R",    2212 },
                        {  11,  "F3OPG",        "Frontal_Inf_Oper_L",   2301 },
                        {  12,  "F3OPD",        "Frontal_Inf_Oper_R",   2302 },
                        {  13,  "F3TG",         "Frontal_Inf_Tri_L",    2311 },
                        {  14,  "F3TD",         "Frontal_Inf_Tri_R",    2312 },
                        {  15,  "F3OG",         "Frontal_Inf_Orb_L",    2321 },
                        {  16,  "F3OD",         "Frontal_Inf_Orb_R",    2322 },
                        {  17,  "ORG",          "Rolandic_Oper_L",      2331 },
                        {  18,  "ORD",          "Rolandic_Oper_R",      2332 },
                        {  19,  "SMAG",         "Supp_Motor_Area_L",    2401 },
                        {  20,  "SMAD",         "Supp_Motor_Area_R",    2402 },
                        {  21,  "COBG",         "Olfactory_L",          2501 },
                        {  22,  "COBD",         "Olfactory_R",          2502 },
                        {  23,  "FMG",          "Frontal_Sup_Medial_L", 2601 },
                        {  24,  "FMD",          "Frontal_Sup_Medial_R", 2602 },
                        {  25,  "FMOG",         "Frontal_Med_Orb_L",    2611 },     // !older version was buggy: Mid instead of Med which duplicated region 9!
                        {  26,  "FMOD",         "Frontal_Med_Orb_R",    2612 },     // !older version was buggy: Mid instead of Med which duplicated region 10!
                        {  27,  "GRG",          "Rectus_L",             2701 },
                        {  28,  "GRD",          "Rectus_R",             2702 },
                        {  29,  "ING",          "Insula_L",             3001 },
                        {  30,  "IND",          "Insula_R",             3002 },
                        {  31,  "CIAG",         "Cingulum_Ant_L",       4001 },
                        {  32,  "CIAD",         "Cingulum_Ant_R",       4002 },
                        {  33,  "CINMG",        "Cingulum_Mid_L",       4011 },
                        {  34,  "CINMD",        "Cingulum_Mid_R",       4012 },
                        {  35,  "CIPG",         "Cingulum_Post_L",      4021 },
                        {  36,  "CIPD",         "Cingulum_Post_R",      4022 },
                        {  37,  "HIPPOG",       "Hippocampus_L",        4101 },
                        {  38,  "HIPPOD",       "Hippocampus_R",        4102 },
                        {  39,  "PARA_HIPPOG",  "ParaHippocampal_L",    4111 },
                        {  40,  "PARA_HIPPOD",  "ParaHippocampal_R",    4112 },
                        {  41,  "AMYGDG",       "Amygdala_L",           4201 },
                        {  42,  "AMYGDD",       "Amygdala_R",           4202 },
                        {  43,  "V1G",          "Calcarine_L",          5001 },
                        {  44,  "V1D",          "Calcarine_R",          5002 },
                        {  45,  "QG",           "Cuneus_L",             5011 },
                        {  46,  "QD",           "Cuneus_R",             5012 },
                        {  47,  "LINGG",        "Lingual_L",            5021 },
                        {  48,  "LINGD",        "Lingual_R",            5022 },
                        {  49,  "O1G",          "Occipital_Sup_L",      5101 },
                        {  50,  "O1D",          "Occipital_Sup_R",      5102 },
                        {  51,  "O2G",          "Occipital_Mid_L",      5201 },
                        {  52,  "O2D",          "Occipital_Mid_R",      5202 },
                        {  53,  "O3G",          "Occipital_Inf_L",      5301 },
                        {  54,  "O3D",          "Occipital_Inf_R",      5302 },
                        {  55,  "FUSIG",        "Fusiform_L",           5401 },
                        {  56,  "FUSID",        "Fusiform_R",           5402 },
                        {  57,  "PAG",          "Postcentral_L",        6001 },
                        {  58,  "PAD",          "Postcentral_R",        6002 },
                        {  59,  "P1G",          "Parietal_Sup_L",       6101 },
                        {  60,  "P1D",          "Parietal_Sup_R",       6102 },
                        {  61,  "P2G",          "Parietal_Inf_L",       6201 },
                        {  62,  "P2D",          "Parietal_Inf_R",       6202 },
                        {  63,  "GSMG",         "SupraMarginal_L",      6211 },
                        {  64,  "GSMD",         "SupraMarginal_R",      6212 },
                        {  65,  "GAG",          "Angular_L",            6221 },
                        {  66,  "GAD",          "Angular_R",            6222 },
                        {  67,  "PQG",          "Precuneus_L",          6301 },
                        {  68,  "PQD",          "Precuneus_R",          6302 },
                        {  69,  "LPCG",         "Paracentral_Lobule_L", 6401 },
                        {  70,  "LPCD",         "Paracentral_Lobule_R", 6402 },
                        {  71,  "NCG",          "Caudate_L",            7001 },
                        {  72,  "NCD",          "Caudate_R",            7002 },
                        {  73,  "NLG",          "Putamen_L",            7011 },
                        {  74,  "NLD",          "Putamen_R",            7012 },
                        {  75,  "PALLG",        "Pallidum_L",           7021 },
                        {  76,  "PALLD",        "Pallidum_R",           7022 },
                        {  77,  "THAG",         "Thalamus_L",           7101 },
                        {  78,  "THAD",         "Thalamus_R",           7102 },
                        {  79,  "HESCHLG",      "Heschl_L",             8101 },
                        {  80,  "HESCHLD",      "Heschl_R",             8102 },
                        {  81,  "T1G",          "Temporal_Sup_L",       8111 },
                        {  82,  "T1D",          "Temporal_Sup_R",       8112 },
                        {  83,  "T1AG",         "Temporal_Pole_Sup_L",  8121 },
                        {  84,  "T1AD",         "Temporal_Pole_Sup_R",  8122 },
                        {  85,  "T2G",          "Temporal_Mid_L",       8201 },
                        {  86,  "T2D",          "Temporal_Mid_R",       8202 },
                        {  87,  "T2AG",         "Temporal_Pole_Mid_L",  8211 },
                        {  88,  "T2AD",         "Temporal_Pole_Mid_R",  8212 },
                        {  89,  "T3G",          "Temporal_Inf_L",       8301 },
                        {  90,  "T3D",          "Temporal_Inf_R",       8302 },
                        {  91,  "CERCRU1G",     "Cerebelum_Crus1_L",    9001 },
                        {  92,  "CERCRU1D",     "Cerebelum_Crus1_R",    9002 },
                        {  93,  "CERCRU2G",     "Cerebelum_Crus2_L",    9011 },
                        {  94,  "CERCRU2D",     "Cerebelum_Crus2_R",    9012 },
                        {  95,  "CER3G",        "Cerebelum_3_L",        9021 },
                        {  96,  "CER3D",        "Cerebelum_3_R",        9022 },
                        {  97,  "CER4_5G",      "Cerebelum_4_5_L",      9031 },
                        {  98,  "CER4_5D",      "Cerebelum_4_5_R",      9032 },
                        {  99,  "CER6G",        "Cerebelum_6_L",        9041 },
                        { 100,  "CER6D",        "Cerebelum_6_R",        9042 },
                        { 101,  "CER7BG",       "Cerebelum_7b_L",       9051 },
                        { 102,  "CER7BD",       "Cerebelum_7b_R",       9052 },
                        { 103,  "CER8G",        "Cerebelum_8_L",        9061 },
                        { 104,  "CER8D",        "Cerebelum_8_R",        9062 },
                        { 105,  "CER9G",        "Cerebelum_9_L",        9071 },
                        { 106,  "CER9D",        "Cerebelum_9_R",        9072 },
                        { 107,  "CER10G",       "Cerebelum_10_L",       9081 },
                        { 108,  "CER10D",       "Cerebelum_10_R",       9082 },
                        { 109,  "VER1_2",       "Vermis_1_2",           9100 },
                        { 110,  "VER3",         "Vermis_3",             9110 },
                        { 111,  "VER4_5",       "Vermis_4_5",           9120 },
                        { 112,  "VER6",         "Vermis_6",             9130 },
                        { 113,  "VER7",         "Vermis_7",             9140 },
                        { 114,  "VER8",         "Vermis_8",             9150 },
                        { 115,  "VER9",         "Vermis_9",             9160 },
                        { 116,  "VER10",        "Vermis_10",            9170 }
                        };
*/
                                        // Official AAL3v1 ROI names:
                                        //  - Some id's have disappeared but are still listed here so that all indexes exist
                                        //  - Values that have indeed disappeared are 0 now, and will be ignored
                                        //  - Old and new versions can also differ in syntax(!), f.ex Cerebellum vs Cerebelum, and 2 identical id's can even have different names!
                                        //  - The ground truth has been chosen to be the file  "AAL3v1_1mm.nii.txt"
const TAALRoi   AAL3v1Codes[ NumAAL3v1Codes ] =
                        {
                        {	  1,	"FAL",	        "Precentral_L",	        0	},
                        {	  2,	"FAR",	        "Precentral_R",	        0	},
                        {	  3,	"F1_2L",	    "Frontal_Sup_2_L",	    0	},
                        {	  4,	"F1_2R",	    "Frontal_Sup_2_R",	    0	},
                        {	  5,	"F2_2L",	    "Frontal_Mid_2_L",	    0	},
                        {	  6,	"F2_2R",	    "Frontal_Mid_2_R",	    0	},
                        {	  7,	"F3OPL",	    "Frontal_Inf_Oper_L",	0	},
                        {	  8,	"F3OPR",	    "Frontal_Inf_Oper_R",	0	},
                        {	  9,	"F3TL",	        "Frontal_Inf_Tri_L",	0	},
                        {	 10,	"F3TR",	        "Frontal_Inf_Tri_R",	0	},
                        {	 11,	"F3O_2L",	    "Frontal_Inf_Orb_2_L",	0	},
                        {	 12,	"F3O_2R",	    "Frontal_Inf_Orb_2_R",	0	},
                        {	 13,	"ORL",	        "Rolandic_Oper_L",	    0	},
                        {	 14,	"ORR",	        "Rolandic_Oper_R",	    0	},
                        {	 15,	"SMAL",	        "Supp_Motor_Area_L",	0	},
                        {	 16,	"SMAR",	        "Supp_Motor_Area_R",	0	},
                        {	 17,	"COBL",	        "Olfactory_L",	        0	},
                        {	 18,	"COBR",	        "Olfactory_R",	        0	},
                        {	 19,	"FML",	        "Frontal_Sup_Medial_L",	0	},
                        {	 20,	"FMR",	        "Frontal_Sup_Medial_R",	0	},
                        {	 21,	"FMOL",	        "Frontal_Med_Orb_L",	0	},
                        {	 22,	"FMOR",	        "Frontal_Med_Orb_R",	0	},
                        {	 23,	"GRL",	        "Rectus_L",	            0	},
                        {	 24,	"GRR",	        "Rectus_R",	            0	},
                        {	 25,	"OFCMEDL",	    "OFCmed_L",	            0	},
                        {	 26,	"OFCMEDR",	    "OFCmed_R",	            0	},
                        {	 27,	"OFCANTL",	    "OFCant_L",	            0	},
                        {	 28,	"OFCANTR",	    "OFCant_R",	            0	},
                        {	 29,	"OFCPOSTL",	    "OFCpost_L",	        0	},
                        {	 30,	"OFCPOSTR",	    "OFCpost_R",	        0	},
                        {	 31,	"OFCLATL",	    "OFClat_L",	            0	},
                        {	 32,	"OFCLATR",	    "OFClat_R",	            0	},
                        {	 33,	"INL",	        "Insula_L",	            0	},
                        {	 34,	"INR",	        "Insula_R",	            0	},
                        {	 35,	"CIAL",	        "Cingulate_Ant_L",	    0	},  // !removed!
                        {	 36,	"CIAR",	        "Cingulate_Ant_R",	    0	},  // !removed!
                        {	 37,	"CINML",	    "Cingulate_Mid_L",	    0	},
                        {	 38,	"CINMR",	    "Cingulate_Mid_R",	    0	},
                        {	 39,	"CIPL",	        "Cingulate_Post_L",	    0	},
                        {	 40,	"CIPR",	        "Cingulate_Post_R",	    0	},
                        {	 41,	"HIPPOL",	    "Hippocampus_L",	    0	},
                        {	 42,	"HIPPOR",	    "Hippocampus_R",	    0	},
                        {	 43,	"PARA_HIPPOL",	"ParaHippocampal_L",	0	},
                        {	 44,	"PARA_HIPPOR",	"ParaHippocampal_R",	0	},
                        {	 45,	"AMYGDL",	    "Amygdala_L",	        0	},
                        {	 46,	"AMYGDR",	    "Amygdala_R",	        0	},
                        {	 47,	"V1L",	        "Calcarine_L",	        0	},
                        {	 48,	"V1R",	        "Calcarine_R",	        0	},
                        {	 49,	"QL",	        "Cuneus_L",	            0	},
                        {	 50,	"QR",	        "Cuneus_R",	            0	},
                        {	 51,	"LINGL",	    "Lingual_L",	        0	},
                        {	 52,	"LINGR",	    "Lingual_R",	        0	},
                        {	 53,	"O1L",	        "Occipital_Sup_L",	    0	},
                        {	 54,	"O1R",	        "Occipital_Sup_R",	    0	},
                        {	 55,	"O2L",	        "Occipital_Mid_L",	    0	},
                        {	 56,	"O2R",	        "Occipital_Mid_R",	    0	},
                        {	 57,	"O3L",	        "Occipital_Inf_L",	    0	},
                        {	 58,	"O3R",	        "Occipital_Inf_R",	    0	},
                        {	 59,	"FUSIL",	    "Fusiform_L",	        0	},
                        {	 60,	"FUSIR",	    "Fusiform_R",	        0	},
                        {	 61,	"PAL",	        "Postcentral_L",	    0	},
                        {	 62,	"PAR",	        "Postcentral_R",	    0	},
                        {	 63,	"P1L",	        "Parietal_Sup_L",	    0	},
                        {	 64,	"P1R",	        "Parietal_Sup_R",	    0	},
                        {	 65,	"P2L",	        "Parietal_Inf_L",	    0	},
                        {	 66,	"P2R",	        "Parietal_Inf_R",	    0	},
                        {	 67,	"GSML",	        "SupraMarginal_L",	    0	},
                        {	 68,	"GSMR",	        "SupraMarginal_R",	    0	},
                        {	 69,	"GAL",	        "Angular_L",	        0	},
                        {	 70,	"GAR",	        "Angular_R",	        0	},
                        {	 71,	"PQL",	        "Precuneus_L",	        0	},
                        {	 72,	"PQR",	        "Precuneus_R",	        0	},
                        {	 73,	"LPCL",	        "Paracentral_Lobule_L",	0	},
                        {	 74,	"LPCR",	        "Paracentral_Lobule_R",	0	},
                        {	 75,	"NCL",	        "Caudate_L",	        0	},
                        {	 76,	"NCR",	        "Caudate_R",	        0	},
                        {	 77,	"NLL",	        "Putamen_L",	        0	},
                        {	 78,	"NLR",	        "Putamen_R",	        0	},
                        {	 79,	"PALLL",	    "Pallidum_L",	        0	},
                        {	 80,	"PALLR",	    "Pallidum_R",	        0	},
                        {	 81,	"THAL",	        "Thalamus_L",	        0	},  // !removed!
                        {	 82,	"THAR",	        "Thalamus_R",	        0	},  // !removed!
                        {	 83,	"HESCHLL",	    "Heschl_L",	            0	},
                        {	 84,	"HESCHLR",	    "Heschl_R",	            0	},
                        {	 85,	"T1L",	        "Temporal_Sup_L",	    0	},
                        {	 86,	"T1R",	        "Temporal_Sup_R",	    0	},
                        {	 87,	"T1AL",	        "Temporal_Pole_Sup_L",	0	},
                        {	 88,	"T1AR",	        "Temporal_Pole_Sup_R",	0	},
                        {	 89,	"T2L",	        "Temporal_Mid_L",	    0	},
                        {	 90,	"T2R",	        "Temporal_Mid_R",	    0	},
                        {	 91,	"T2AL",	        "Temporal_Pole_Mid_L",	0	},
                        {	 92,	"T2AR",	        "Temporal_Pole_Mid_R",	0	},
                        {	 93,	"T3L",	        "Temporal_Inf_L",	    0	},
                        {	 94,	"T3R",	        "Temporal_Inf_R",	    0	},
                        {	 95,	"CERCRU1L",	    "Cerebellum_Crus1_L",	0	},  // "Cerebellum" in file "AAL3v1_1mm.nii.txt" instead of "Cerebelum" in file "ROI_MNI_V7_1mm_vol.txt"
                        {	 96,	"CERCRU1R",	    "Cerebellum_Crus1_R",	0	},
                        {	 97,	"CERCRU2L",	    "Cerebellum_Crus2_L",	0	},
                        {	 98,	"CERCRU2R",	    "Cerebellum_Crus2_R",	0	},
                        {	 99,	"CER3L",	    "Cerebellum_3_L",	    0	},
                        {	100,	"CER3R",	    "Cerebellum_3_R",	    0	},
                        {	101,	"CER4_5L",	    "Cerebellum_4_5_L",	    0	},
                        {	102,	"CER4_5R",	    "Cerebellum_4_5_R",	    0	},
                        {	103,	"CER6L",	    "Cerebellum_6_L",	    0	},
                        {	104,	"CER6R",	    "Cerebellum_6_R",	    0	},
                        {	105,	"CER7BL",	    "Cerebellum_7b_L",	    0	},
                        {	106,	"CER7BR",	    "Cerebellum_7b_R",	    0	},
                        {	107,	"CER8L",	    "Cerebellum_8_L",	    0	},
                        {	108,	"CER8R",	    "Cerebellum_8_R",	    0	},
                        {	109,	"CER9L",	    "Cerebellum_9_L",	    0	},
                        {	110,	"CER9R",	    "Cerebellum_9_R",	    0	},
                        {	111,	"CER10L",	    "Cerebellum_10_L",	    0	},
                        {	112,	"CER10R",	    "Cerebellum_10_R",	    0	},
                        {	113,	"VER1_2",	    "Vermis_1_2",	        0	},
                        {	114,	"VER3",	        "Vermis_3",	            0	},
                        {	115,	"VER4_5",	    "Vermis_4_5",	        0	},
                        {	116,	"VER6",	        "Vermis_6",	            0	},
                        {	117,	"VER7",	        "Vermis_7",	            0	},
                        {	118,	"VER8",	        "Vermis_8",	            0	},
                        {	119,	"VER9",	        "Vermis_9",	            0	},
                        {	120,	"VER10",	    "Vermis_10",	        0	},
                        {	121,	"tAVL",	        "Thal_AV_L",	        0	},
                        {	122,	"tAVR",	        "Thal_AV_R",	        0	},
                        {	123,	"tLPL",	        "Thal_LP_L",	        0	},
                        {	124,	"tLPR",	        "Thal_LP_R",	        0	},
                        {	125,	"tVAL",	        "Thal_VA_L",	        0	},
                        {	126,	"tVAR",	        "Thal_VA_R",	        0	},
                        {	127,	"tVLL",	        "Thal_VL_L",	        0	},
                        {	128,	"tVLR",	        "Thal_VL_R",	        0	},
                        {	129,	"tVPLL",	    "Thal_VPL_L",	        0	},
                        {	130,	"tVPLR",	    "Thal_VPL_R",	        0	},
                        {	131,	"tILL",	        "Thal_IL_L",	        0	},
                        {	132,	"tILR",	        "Thal_IL_R",	        0	},
                        {	133,	"tReL",	        "Thal_Re_L",	        0	},
                        {	134,	"tReR",	        "Thal_Re_R",	        0	},
                        {	135,	"tMDmL",	    "Thal_MDm_L",	        0	},
                        {	136,	"tMDmR",	    "Thal_MDm_R",	        0	},
                        {	137,	"tMDlL",	    "Thal_MDl_L",	        0	},
                        {	138,	"tMDlR",	    "Thal_MDl_R",	        0	},
                        {	139,	"tLGNL",	    "Thal_LGN_L",	        0	},
                        {	140,	"tLGNR",	    "Thal_LGN_R",	        0	},
                        {	141,	"tMGNL",	    "Thal_MGN_L",	        0	},
                        {	142,	"tMGNR",	    "Thal_MGN_R",	        0	},
                        {	143,	"tPuIL",	    "Thal_PuI_L",	        0	},
                        {	144,	"tPuIR",	    "Thal_PuI_R",	        0	},
                        {	145,	"tPuML",	    "Thal_PuM_L",	        0	},
                        {	146,	"tPuMR",	    "Thal_PuM_R",	        0	},
                        {	147,	"tPuAL",	    "Thal_PuA_L",	        0	},
                        {	148,	"tPuAR",	    "Thal_PuA_R",	        0	},
                        {	149,	"tPuLL",	    "Thal_PuL_L",	        0	},
                        {	150,	"tPuLR",	    "Thal_PuL_R",	        0	},
                        {	151,	"ACCsubL",	    "ACC_sub_L",	        0	},
                        {	152,	"ACCsubR",	    "ACC_sub_R",	        0	},
                        {	153,	"ACCpreL",	    "ACC_pre_L",	        0	},
                        {	154,	"ACCpreR",	    "ACC_pre_R",	        0	},
                        {	155,	"ACCsupL",	    "ACC_sup_L",	        0	},
                        {	156,	"ACCsupR",	    "ACC_sup_R",	        0	},
                        {	157,	"NAccL",	    "N_Acc_L",	            0	},  // in file "AAL3v1_1mm.nii.txt"
                        {	158,	"NAccR",	    "N_Acc_R",	            0	},  // in file "AAL3v1_1mm.nii.txt"
//                      {	157,	"VentStrL",	    "Vent_Str_L",	        0	},  // in file "ROI_MNI_V7_1mm_vol.txt"
//                      {	158,	"VentStrR",	    "Vent_Str_R",	        0	},  // in file "ROI_MNI_V7_1mm_vol.txt"
                        {	159,	"VTAL",	        "VTA_L",	            0	},
                        {	160,	"VTAR",	        "VTA_R",	            0	},
                        {	161,	"SNpcL",	    "SN_pc_L",	            0	},
                        {	162,	"SNpcR",	    "SN_pc_R",	            0	},
                        {	163,	"SNprL",	    "SN_pr_L",	            0	},
                        {	164,	"SNprR",	    "SN_pr_R",	            0	},
                        {	165,	"RedNL",	    "Red_N_L",	            0	},
                        {	166,	"RedNR",	    "Red_N_R",	            0	},
                        {	167,	"LCL",	        "LC_L",	                0	},
                        {	168,	"LCR",	        "LC_R",	                0	},
                        {	169,	"RapheD",	    "Raphe_D",	            0	},
                        {	170,	"RapheM",	    "Raphe_M",	            0	}
                        };


//----------------------------------------------------------------------------
//----------------------------------------------------------------------------

}
