//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDM_MDI                         100
#define IDB_FORWARD                     201
#define IDB_BACKWARD                    202
#define IDB_FASTFORWARD                 203
#define IDB_FASTBACKWARD                204
#define IDB_PAGEFORWARD                 205
#define IDB_PAGEBACKWARD                206
#define IDB_UP                          207
#define IDB_DOWN                        208
#define IDB_RANGECURSOR                 209
#define IDB_EXTTRACKSV                  210
#define IDB_COMPTRACKSV                 211
#define IDB_EXTTRACKSH                  212
#define IDB_COMPTRACKSH                 213
#define IDB_LESSTRACKS                  214
#define IDB_MORETRACKS                  215
#define IDB_TRACKSSUPER                 216
#define IDB_VERTUNITS                   217
#define IDB_HORIZUNITS                  218
#define IDB_STYLEWINDOW                 219
#define IDB_SHOWMARKERS                 220
#define IDB_NEXTMARKER                  221
#define IDB_PREVMARKER                  222
#define IDB_LESSPSEUDOTRACKS            223
#define IDB_MOREPSEUDOTRACKS            224
#define IDB_FILTER                      225
#define IDB_ADDMARKER                   226
#define IDB_SHOWSD                      227
#define IDB_SPLITWINDOW                 228
#define IDB_2EEGS                       229
#define IDB_HSCROLL                     230
#define IDB_FLIPVERT                    231
#define IDB_FILLING                     232
#define IDB_NEXTSESSION                 233
#define IDB_SETAVGREF                   234
#define IDB_NEXTROI                     235
#define IDB_AVERAGEROIS                 236
#define IDB_SHOWMIN                     249
#define IDB_SHOWMAX                     250
#define IDB_ISINCBRIGHT                 251
#define IDB_ISDECBRIGHT                 252
#define IDB_FIXEDSCALE                  253
#define IDB_NEXTIS                      254
#define IDB_ISINCCONTRAST               255
#define IDB_ISDECCONTRAST               256
#define IDB_QUADRANT                    257
#define IDB_RANGEAVE                    260
#define IDB_RANGESEQ                    261
#define IDB_RANGEANI                    262
#define IDB_RGESTEPINC                  263
#define IDB_RGESTEPDEC                  264
#define IDB_PREVREG                     270
#define IDB_NEXTREG                     271
#define IDB_RESETREG                    272
#define IDB_SEARCHBESTREGCURSOR         273
#define IDB_SEARCHBESTREGGLOBAL         274
#define IDB_GTVFIT                      280
#define IDB_GTVKEEPSIZE                 281
#define IDB_GTVSTANDSIZE                282
#define IDB_ADDTOGROUP                  283
#define IDB_SEGMENT                     284
#define IDB_FITSEGMENT                  285
#define IDB_SHOWELEC                    330
#define IDB_SHOWTRIANGLES               331
#define IDB_SPINCBRIGHT                 332
#define IDB_SPDECBRIGHT                 333
#define IDB_SPCOLOR                     334
#define IDB_SHOWZERO                    335
#define IDB_SHOWPMMINMAX                336
#define IDB_MONTAGE                     337
#define IDB_SHOWELNAMES                 338
#define IDB_NEXTXYZ                     339
#define IDB_SPINCCONTRAST               340
#define IDB_SPDECCONTRAST               341
#define IDB_FLATVIEW                    342
#define IDB_PAIRVIEW                    343
#define IDB_SHOWTRACKS                  344
#define IDB_MRICORONAL                  350
#define IDB_MRISAGITTAL                 351
#define IDB_MRITRANSVERSE               352
#define IDB_LESSSLICES                  360
#define IDB_MORESLICES                  361
#define IDB_FIRSTSLICEFWD               362
#define IDB_FIRSTSLICEBWD               363
#define IDB_LASTSLICEFWD                364
#define IDB_LASTSLICEBWD                365
#define IDB_NEXTMRI                     366
#define IDB_SHOWMRI                     367
#define IDB_SHOWIS                      368
#define IDB_FINDMINMAX                  369
#define IDB_SHOWSP                      370
#define IDB_ADDVIEW                     401
#define IDB_SYNCVIEWS                   402
#define IDB_SYNCZERO                    403
#define IDB_2OBJECT                     500
#define IDB_SURFACEMODE                 501
#define IDB_ORIENT                      502
#define IDB_MAGNIFIER                   503
#define IDB_SOLPSHOWNAMES               600
#define IDB_SHOW3DIS                    700
#define IDB_SHOW2DIS                    701
#define IDB_SHOW3DMRI                   702
#define IDB_SHOWVECTORSIS               703
#define IDB_FLIPX                       803
#define IDB_FLIPY                       804
#define IDB_FLIPZ                       805
#define IDB_FLIPXY                      806
#define IDB_FLIPYZ                      807
#define IDB_FLIPXZ                      808
#define IDB_CUTPLANEX                   809
#define IDB_CUTPLANEY                   810
#define IDB_CUTPLANEZ                   811
#define IDB_CUTPLANEMODE                812
#define IDB_CAPPING                     813
#define IDB_PLANEMODE                   814
#define IDB_ISOMANUAL                   815
#define IDB_ISOVALUE                    816
#define IDB_CUTPLANECORONAL             817
#define IDB_CUTPLANETRANSVERSE          818
#define IDB_CUTPLANESAGITTAL            819
#define IDB_COLORIZESURFACE             820
#define IDB_EDITING                     821
#define IDB_FREQDISPLAY_EFT             900
#define IDB_FREQDISPLAY_ET              901
#define IDB_FREQDISPLAY_FTE             902
#define IDB_NEXTFREQ                    903
#define IDB_PREVIOUSFREQ                904
#define IDB_MOREFREQS                   905
#define IDB_LESSFREQS                   906
#define IDB_FREQNORMALIZE               907
#define IDB_FREQDISPLAY_SPECTRUM        908
#define IDB_FREQDISPLAY_EF              909
#define IDB_FREQDISPLAY_FE              910
#define IDB_AVERAGETRACKS               911
#define IDB_DISPLAYINTENSITY            912
#define IDB_SPLASH                      1000
#define IDI_MDIAPPLICATION              1001
#define IDI_DOC                         1002
#define IDI_EEGTEXT                     1003
#define IDI_EEGBINARY                   1004
#define IDI_EEGSD                       1005
#define IDI_MRK                         1006
#define IDI_MTG                         1007
#define IDI_TVA                         1008
#define IDI_CALIBRATION                 1009
#define IDI_XYZCOORD                    1010
#define IDI_MRI                         1011
#define IDI_LEADFIELD                   1012
#define IDI_INVERSEMATRIX               1013
#define IDI_INVERSERESULTS              1014
#define IDI_SPCOORD                     1015
#define IDI_SPIRR                       1016
#define IDI_LM                          1017
#define IDI_SEG                         1018
#define IDI_DATA                        1019
#define IDI_FREQ                        1020
#define IDI_VERBOSE                     1021
#define IDI_ROIS                        1022
#define CM_EDITCOPYMF                   1100
#define CM_EDITCOPYBM                   1101
#define CM_EXPMETAFILE                  1102
#define CM_EXPBITMAP                    1103
#define CM_EXPTXT                       1104
#define CM_INTERPOL_Y                   1120
#define CM_INTERPOL_N                   1121
#define CM_EXTRAPOL_Y                   1122
#define CM_EXTRAPOL_N                   1123
#define CM_SHOWCOLORSCALE               1124
#define CM_SHOWAXIS                     1125
#define CM_SHOWORIENTATION              1126
#define CM_SHOWSEQUENCELABEL            1127
#define CM_SHOWINFOS                    1128
#define CM_SHOWSIZEBOX                  1129
#define CM_SHOWBOUNDINGBOX              1130
#define CM_SHOWALL                      1131
#define CM_HIDEALL                      1132
#define CM_SHIFTDEPTHRANGE              1140
#define CM_SHIFTDEPTHRANGE0             1141
#define CM_SHIFTDEPTHRANGE1             1142
#define CM_SHIFTDEPTHRANGE2             1143
#define CM_SHIFTDEPTHRANGE3             1144
#define CM_SHIFTDEPTHRANGE4             1145
#define CM_COMPUTINGRIS                 1201
#define CM_RISTOVOLUME                  1202
#define CM_RISTOPOINTS                  1203
#define CM_EEGUSERSCALE                 1250
#define CM_SPUSERSCALE                  1251
#define CM_ISUSERSCALE                  1252
#define CM_EEGREF                       1302
#define CM_EEGREFAVG                    1303
#define CM_EEGREFNONE                   1305
#define CM_EEGREFMONTAGE                1306
#define CM_EEGREFELECSINGLE             1307
#define CM_EEGREFELECMULTIPLE           1308
#define CM_EEGPENSIZE                   1321
#define CM_EEGCONDEXPORT                1322
#define CM_EEGTIMERELATIVE              1323
#define CM_EEGTIMEABSOLUTE              1324
#define CM_EEGBASELINE                  1325
#define CM_EEGRESETFILLING              1326
#define CM_EEGNEXTSESSION               1327
#define CM_EEGRESETSCALING              1328
#define CM_EEGVOIDFILLING               1329
#define CM_EEGFREQANALYSIS              1330
#define CM_EEGSETOFFSET                 1331
#define CM_EEGRESETOFFSET               1332
#define CM_EEGTIMERELATIVETO            1333
#define CM_EEGTIME0                     1334
#define CM_EEGSHOWTIME                  1335
#define CM_EEGSHOWDATE                  1336
#define CM_EEGSAMPLINGFREQUENCY         1337
#define CM_DOCWIN_RESTORE               1400
#define CM_DOCWIN_MIN                   1401
#define CM_DOCWIN_CLOSE                 1402
#define CM_DOCWIN_TILE                  1403
#define CM_ALLWIN_MIN                   1404
#define CM_ALLWIN_RESTORE               1405
#define CM_ALLWIN_PANTILE               1406
#define CM_ALLWIN_RELOADGADGETS         1407
#define CM_GTV_MIN                      1408
#define CM_GTV_RESTORE                  1409
#define CM_WINSIZE_INC                  1410
#define CM_WINSIZE_INCR                 1411
#define CM_WINSIZE_INCL                 1412
#define CM_WINSIZE_INCT                 1413
#define CM_WINSIZE_INCB                 1414
#define CM_WINSIZE_DEC                  1415
#define CM_WINSIZE_DECR                 1416
#define CM_WINSIZE_DECL                 1417
#define CM_WINSIZE_DECT                 1418
#define CM_WINSIZE_DECB                 1419
#define CM_KEEPSEL                      1450
#define CM_REMOVESEL                    1451
#define CM_CLEARSEL                     1452
#define CM_SELECTALL                    1453
#define CM_SELECTALLVISIBLE             1454
#define CM_INVERTSEL                    1455
#define CM_ABOVESEL                     1456
#define CM_INPUTSEL                     1457
#define CM_SHOWSELNAMES                 1458
#define CM_SHOWSELINDEXES               1459
#define CM_BADSET                       1460
#define CM_BADNONE                      1461
#define CM_BADRESET                     1462
#define CM_BADKEEP                      1463
#define CM_BADEXCLUDE                   1464
#define CM_BADSELECT                    1465
#define CM_BADDESELECT                  1466
#define CM_BADSELECTNON                 1467
#define CM_BADAUXSELECTNON              1468
#define CM_AUXSET                       1470
#define CM_AUXNONE                      1471
#define CM_AUXRESET                     1472
#define CM_AUXTODEFAULT                 1473
#define CM_AUXKEEP                      1474
#define CM_AUXEXCLUDE                   1475
#define CM_AUXSELECT                    1476
#define CM_AUXDESELECT                  1477
#define CM_AUXSELECTNON                 1478
#define CM_ANALYZESELFLAT               1480
#define CM_ANALYZESELHIGH               1481
#define CM_ANALYZESELGFP                1482
#define CM_ANALYZESELNOISY              1483
#define CM_ANALYZESELARTEFACTS          1484
#define IDM_EEG                         1500
#define IDM_SP                          1501
#define IDM_POTENTIALS                  1502
#define IDM_XYZ                         1503
#define IDM_IS                          1504
#define IDM_MRI                         1506
#define IDM_INVERSE                     1507
#define IDM_LM                          1508
#define IDM_ROI                         1510
#define CM_FCEP2EPH                     1601
#define CM_FCEPH2EP                     1602
#define CM_FCTXT2IS                     1603
#define CM_FCDM2NDM                     1604
#define CM_FILESCONVERSIONVRBTOTVA      1605
#define CM_MLLXE                        1606
#define CM_MLLIE                        1607
#define CM_MLLSR                        1608
#define CM_FCEPH2RIS                    1609
#define CM_SPLITFREQBYFREQUENCY         1609
#define CM_FCRIS2EPH                    1610
#define CM_SPLITFREQBYELECTRODE         1610
#define CM_SPLITFREQBYTIME              1611
#define CM_MERGEFREQBYFREQUENCY         1612
#define CM_SPLITMATFILES                1613
#define CM_EEGMRKTRIGGERTOMARKER        1701
#define CM_EEGMRKCLEARALL               1702
#define CM_EEGMRKNONE                   1703
#define CM_EEGMRKTRIGGER                1704
#define CM_EEGMRKMARKER                 1705
#define CM_EEGMRKEVENT                  1706
#define CM_EEGMRKALL                    1707
#define CM_EEGMRKDELETE                 1708
#define CM_EEGMRKSELFILE                1709
#define CM_EEGMRKADDFILE                1710
#define CM_EEGMRKSCANEEG                1711
#define CM_EEGMRKMANAGE                 1712
#define CM_EEGMRKSPLIT                  1713
#define CM_EEGMRKDELETENAME             1715
#define CM_EEGMRKMERGEOVERLAPPING       1717
#define CM_EEGMRKMERGECONTIGUOUS        1718
#define CM_EEGMRKSEARCH                 1719
#define CM_EEGMRKSEARCHNEXT             1720
#define CM_EEGMRKSEARCHPREVIOUS         1721
#define CM_EEGMRKDISPLAYFILTER          1722
#define CM_EEGMRKSCANBADEPOCHS          1723
#define CM_EEGMRKGENERATE               1724
#define CM_EEGMRKOVERWRITENAMES         1730
#define CM_EEGMRKSUBSTITUTENAMES        1731
#define CM_EEGMRKREGEXPNAMES            1732
#define CM_EEGMRKQUICKRESET             1740
#define CM_EEGMRKQUICK1                 1741
#define CM_EEGMRKQUICK2                 1742
#define CM_EEGMRKQUICK3                 1743
#define CM_EEGMRKQUICK4                 1744
#define CM_EEGMRKQUICK5                 1745
#define CM_EEGMRKQUICK6                 1746
#define CM_EEGMRKQUICK7                 1747
#define CM_EEGMRKQUICK8                 1748
#define CM_EEGMRKQUICK9                 1749
#define CM_SEARCHTFMAX                  1750
#define CM_OPENSEG                      1751
#define CM_OPENTEMPLATES                1752
#define CM_OPENFITTINGTEMPLATES1        1753
#define CM_OPENFITTINGTEMPLATES2        1754
#define CM_OPENSEGVERBOSE               1755
#define CM_OPENSTATSFITTING             1756
#define CM_SELECTSEGMENTSFROMLIST       1757
#define CM_SELECTSEGMENTSFROMCURSOR     1758
#define CM_NEXTSEGMENT                  1759
#define CM_PREVSEGMENT                  1760
#define CM_SETTIMEWINDOW                1761
#define CM_SEPARATOR                    1762
#define CM_GOTOTIME                     1763
#define CM_SELECTALLTIME                1764
#define CM_EASYPUBLISH                  1800
#define CM_DESYNCALL                    2100
#define CM_SYNCALL                      2101
#define CM_DESYNCBETWEENEEG             2102
#define CM_SYNCBETWEENEEG               2103
#define CM_COMMANDSCLONING              2104
#define CM_FILENEWEMPTYLM               2200
#define CM_FILENEWLM                    2201
#define CM_FILENEWLMFROMEXISTING        2202
#define CM_FILENEWXYZ                   2203
#define CM_MRIDOWNSAMPLING              2300
#define CM_MRINEWORIGIN                 2301
#define CM_NEWBACKTHRESH                2400
#define CM_INTERPOLATE                  2500
#define CM_AVERAGING                    2501
#define CM_SEGMENTEEG                   2502
#define CM_FITTING                      2503
#define CM_EXPORTTRACKS                 2504
#define CM_FREQANALYSIS                 2505
#define CM_GEOMETRYTRANSFORM            2506
#define CM_DOWNSAMPLEMRI                2508
#define CM_NORMALIZEMRI                 2509
#define CM_CREATEROIS                   2510
#define CM_FILECALCULATOR               2511
#define CM_CREATEINVERSESOLUTIONS       2512
#define CM_AVERAGEXYZ                   2513
#define CM_SKULLSTRIPPING               2514
#define CM_MRICOREGISTRATION            2516
#define CM_CUTBRAINSTEM                 2517
#define CM_CORRELATEFILES               2519
#define CM_SCANTRIGGERS                 2520
#define CM_HISTOTIMERAW                 2521
#define CM_HISTOTIMESMOOTH              2522
#define CM_HISTOTIMELOG                 2523
#define CM_HISTOTIMECDF                 2524
#define CM_HISTOTRACKSRAW               2525
#define CM_HISTOTRACKSSMOOTH            2526
#define CM_HISTOTRACKSLOG               2527
#define CM_HISTOTRACKSCDF               2528
#define CM_HISTOALLRAW                  2610
#define CM_HISTOALLSMOOTH               2611
#define CM_HISTOALLLOG                  2612
#define CM_HISTOALLCDF                  2613
#define CM_COMPUTECENTROIDEEG           2530
#define CM_COMPUTECENTROIDRIS           2531
#define CM_STANDARDIZETRACKS            2533
#define CM_STANDARDIZERIS               2534
#define CM_BATCHAVERAGEEEG              2535
#define CM_BATCHAVERAGEERRORDATA        2536
#define CM_BATCHAVERAGERIS              2537
#define CM_BATCHAVERAGEFREQ             2538
#define CM_GENERATEDATAEEG              2540
#define CM_GENERATEDATARIS              2541
#define CM_GENERATERANDOMDATA           2542
#define CM_ANALYZEGENERATEDATAEEG       2543
#define CM_ANALYZEGENERATEDATARIS       2544
#define CM_ANALYZEGENERATEDATAALTSRC    2545
#define CM_PCA                          2550
#define CM_ICA                          2551
#define CM_STATISTICSTRACKS             2553
#define CM_STATISTICSRIS                2554
#define CM_STATISTICSFREQ               2555
#define CM_TEMPLATEMRI                  2556
#define CM_MERGINGMRIMASKS              2557
#define CM_COREGISTRATION               2558
#define CM_DOWNSAMPLINGELECTRODES       2559
#define CM_TOOLSHELP                    2599
#define CM_RESETREGISTRY                2600
#define CM_CLEARREGISTRY                2601
#define CM_GRAPHICACCELAUTO             2602
#define CM_GRAPHICACCELON               2603
#define CM_GRAPHICACCELOFF              2604
#define CM_GRAPHIC3DTEXTURESAUTO        2605
#define CM_GRAPHIC3DTEXTURESON          2606
#define CM_GRAPHIC3DTEXTURESOFF         2607
#define CM_FREQ3DTEXT                   2700
#define CM_FREQRESETSCALING             2701
#define CM_FREQSAVESCALING              2702
#define CM_INVERSEAVERAGEBEFORE         2800
#define CM_INVERSEAVERAGEAFTER          2801
#define CM_EXPORTXYZKEEPSEL             2900
#define CM_EXPORTXYZREMOVESEL           2901
#define CM_EXPORTXYZDELAUNAY            2902
#define CM_RESETORIENTATION             3000
#define CM_SETORIENTATION               3001
#define CM_OPERATIONAND                 3100
#define CM_OPERATIONOR                  3101
#define CM_OPERATIONXOR                 3102
#define CM_OPERATIONCLEAR               3103
#define CM_OPERATIONFILL                3104
#define CM_OPERATIONREPLACE             3105
#define CM_OPERATIONADD                 3106
#define CM_OPERATIONSUB                 3107
#define CM_OPERATIONMULT                3108
#define CM_OPERATIONDIV                 3109
#define CM_FILTERMEAN                   4000
#define CM_FILTERGAUSSIAN               4010
#define CM_FILTERANISOGAUSSIAN          4011
#define CM_FILTERMIN                    4020
#define CM_FILTERMAX                    4021
#define CM_FILTERMINMAX                 4022
#define CM_FILTERRANGE                  4023
#define CM_FILTERMAXMODE                4024
#define CM_FILTERMEDIAN                 4030
#define CM_FILTERMEANSUB                4031
#define CM_FILTERMAD                    4032
#define CM_FILTERSD                     4033
#define CM_FILTERSDINV                  4034
#define CM_FILTERMADSD                  4035
#define CM_FILTERCOV                    4036
#define CM_FILTERMCOV                   4037
#define CM_FILTERMODE                   4038
#define CM_FILTERENTROPY                4039
#define CM_FILTERPERCENTFULL            4040
#define CM_FILTERCUTBELOWFULL           4041
#define CM_FILTERSAV                    4042
#define CM_FILTERCOMPACTNESS            4043
#define CM_FILTERLOGMEANDIV             4044
#define CM_FILTERSNR                    4045
#define CM_FILTERLOGCOV                 4046
#define CM_FILTERLOGMCOV                4047
#define CM_FILTERLOGMEANSUB             4048
#define CM_FILTERMEANDIV                4049
#define CM_FILTERERODE                  4050
#define CM_FILTERDILATE                 4051
#define CM_FILTERCLOSE                  4052
#define CM_FILTEROPEN                   4053
#define CM_FILTERTHINNING               4054
#define CM_FILTERWATERFALLRIDGES        4055
#define CM_FILTERWATERFALLVALLEYS       4056
#define CM_FILTERMORPHGRADIENT          4057
#define CM_FILTERMORPHGRADIENTINT       4058
#define CM_FILTERMORPHGRADIENTEXT       4059
#define CM_FILTERTHRESHOLD              4060
#define CM_FILTERBINARIZE               4061
#define CM_FILTERTOMASK                 4062
#define CM_FILTERIREVERT                4063
#define CM_FILTERLESSNEIGH              4064
#define CM_FILTERMORENEIGH              4065
#define CM_FILTERRELAX                  4066
#define CM_FILTERKEEPBIGGEST            4067
#define CM_FILTERKEEPCOMPACT            4068
#define CM_FILTERKEEPBIGGEST2           4069
#define CM_FILTERKEEPCOMPACT2           4070
#define CM_FILTERCLUSTERSTOREGIONS      4071
#define CM_FILTERTHRESHOLDABOVE         4072
#define CM_FILTERTHRESHOLDBELOW         4073
#define CM_FILTERSYMMETRIZE             4074
#define CM_FILTERGRADIENT               4080
#define CM_FILTERCANNY                  4081
#define CM_FILTERLAPLACIAN              4082
#define CM_FILTERHESSIANEIGENMAX        4083
#define CM_FILTERHESSIANEIGENMIN        4084
#define CM_FILTERKCURVATURE             4086
#define CM_FILTERKCCURVATURE            4087
#define CM_FILTERBIASFIELD              4090
#define CM_FILTERSEGMENTTISSUES         4091
#define CM_FILTERSEGMENTCSF             4092
#define CM_FILTERSEGMENTGREY            4093
#define CM_FILTERSEGMENTWHITE           4094
#define CM_FILTERMASKTOSP               4095
#define CM_FILTERHISTOCOMPUTE           4100
#define CM_FILTERHISTOCOMPUTELOG        4101
#define CM_FILTERHISTOCOMPUTETXT        4102
#define CM_FILTERHISTOEQUALIZE          4103
#define CM_FILTERHISTOCOMPACT           4104
#define CM_FILTERHISTOEQUALIZEBRAIN     4105
#define CM_FILTERCDFCOMPUTE             4106
#define CM_FILTERRANK                   4107
#define CM_FILTERRANKRAMP               4108
#define CM_FILTERINTENSITYADD           4200
#define CM_FILTERINTENSITYSUB           4201
#define CM_FILTERINTENSITYMULT          4202
#define CM_FILTERINTENSITYDIV           4203
#define CM_FILTERINTENSITYREMAP         4204
#define CM_FILTERINTENSITYOPPOSITE      4205
#define CM_FILTERINTENSITYINVERT        4206
#define CM_FILTERINTENSITYABS           4207
#define CM_FILTERINTENSITYNORM          4208
#define CM_FILTERKEEPVALUE              4209
#define CM_HEADCLEANUP                  4210
#define CM_FILTERRESIZE                 4300
#define IDD_AVERAGE1                    5001
#define IDD_AVERAGE2                    5002
#define IDD_AVERAGE3                    5003
#define IDD_AVERAGECONTROL              5004
#define IDD_TRACKSFILTERS               5005
#define IDD_EXPORTTRACKS                5006
#define IDD_INTERPOLATE                 5009
#define IDD_SCANMARKERS                 5010
#define IDD_FREQANALYSIS                5011
#define IDD_STATISTICS1                 5012
#define IDD_STATISTICS2                 5013
#define IDD_CREATEROIS                  5014
#define IDD_CALCULATOR                  5015
#define IDD_INVERSEMATRICES             5016
#define IDD_SEGMENT1                    5018
#define IDD_SEGMENT2                    5019
#define IDD_FITTING1                    5020
#define IDD_FITTING2                    5021
#define IDD_FITTING3                    5022
#define IDD_MRIPREPROCESSING            5023
#define IDD_RISCOMPUTATION              5024
#define IDD_RISTOVOLUME                 5025
#define IDD_COREGISTRATION              5026
#define IDD_INPUTDIALOG3                5090
#define IDD_INPUTDIALOG6                5091
#define IDD_INPUTDIALOG9                5092
#define IDC_ADD2LIST                    5107
#define IDC_BROWSEEEG                   5108
#define IDC_BROWSETVA                   5109
#define IDC_BROWSECI                    5110
#define IDC_CBEEG                       5112
#define IDC_CBTVA                       5113
#define IDC_CBCI                        5114
#define IDC_CBTRG                       5115
#define IDC_OUTFILEE                    5116
#define IDC_REMFROMLIST                 5117
#define IDC_REPLFIELD                   5118
#define IDC_EXYZFILE                    5119
#define IDC_BROWSEXYZ                   5120
#define IDC_READPARAMS                  5121
#define IDC_WRITEPARAMS                 5122
#define IDC_CBSESSION                   5123
#define IDC_CLEARLISTS                  5124
#define IDC_SORTLISTS                   5125
#define IDC_SORTLIST                    5125
#define IDC_CHK_EXCL                    5200
#define IDC_CHK_AMPL                    5201
#define IDC_CHKUD_AMPL                  5202
#define IDC_CHKE_AMPL                   5203
#define IDC_CHKE_EXCL                   5204
#define IDC_SOE_1TF                     5205
#define IDC_SOB_1TF                     5206
#define IDC_SOB_TRIGGER                 5207
#define IDC_SOB_OFFSET                  5208
#define IDC_SOB_RTIME                   5209
#define IDC_SOE_OFFSET                  5210
#define IDC_DE_PRE                      5212
#define IDC_DE_POST                     5213
#define IDC_DE_TOTAL                    5214
#define IDC_AUXCHANNELS                 5217
#define IDC_BLCE_POST                   5218
#define IDC_BLCE_PRE                    5219
#define IDC_BASELINECORR                5220
#define IDC_SAVEEXCLUDED                5221
#define IDC_FILTERDATA                  5222
#define IDC_SAVESE                      5225
#define IDC_SAVESD                      5226
#define IDC_SAVEEPOCH                   5227
#define IDC_GFPNORMALIZED               5228
#define IDC_AVERAGEREF                  5229
#define IDC_FILTERDISPLAY               5230
#define IDC_FILTERNO                    5231
#define IDC_SETFILTERS                  5232
#define IDC_AUXNAMES                    5233
#define IDC_INTERPOLATE                 5233
#define IDC_AUXMIN                      5234
#define IDC_SAVEAVG                     5234
#define IDC_AUXMAX                      5235
#define IDC_SAVESUM                     5235
#define IDC_RESTORETRACKS               5236
#define IDC_SAVESUMSQR                  5236
#define IDC_GROUPTRACKS                 5237
#define IDC_SAVEEPOCHSMULTIFILES        5237
#define IDC_ACCEPTUNTILBAD              5238
#define IDC_SAVEEPOCHSSINGLEFILE        5238
#define IDC_REJECTUNTILOK               5239
#define IDC_GETFILES                    5239
#define IDC_PROGRESSBAR                 5240
#define IDC_MERGETRIGGERS               5240
#define IDC_SPLITTRIGGERS               5241
#define IDC_SOE_1TF_MS                  5242
#define IDC_SOE_OFFSET_MS               5243
#define IDC_DE_PRE_MS                   5244
#define IDC_DE_POST_MS                  5245
#define IDC_DE_TOTAL_MS                 5246
#define IDC_BLCE_POST_MS                5247
#define IDC_BLCE_PRE_MS                 5248
#define IDC_CHECKAUX                    5249
#define IDC_AUXTHRESHOLD                5250
#define IDC_AUXOVERRIDE                 5251
#define IDC_CHECKEL                     5252
#define IDC_ORIGINMARKER                5253
#define IDC_AVERAGEERP                  5254
#define IDC_AVERAGEGRANDMEAN            5255
#define IDC_ACCEPTALL                   5256
#define IDC_ORDEREDBY                   5257
#define IDC_ORDEREDBYLIST               5258
#define IDC_CURRFILE                    5300
#define IDC_CURRTRIGG                   5301
#define IDC_MAXTRIGG                    5302
#define IDC_NUMTRIGGACC                 5303
#define IDC_NUMTRIGGREJ                 5304
#define IDC_ACCTRIGG                    5305
#define IDC_REJTRIGG                    5306
#define IDC_ACCNEXT                     5307
#define IDC_REJNEXT                     5308
#define IDC_ANE                         5309
#define IDC_ANUD                        5310
#define IDC_RNE                         5311
#define IDC_RNUD                        5312
#define IDC_CURRCHANNEL                 5313
#define IDC_CHANNMIN                    5314
#define IDC_CHANNMAX                    5315
#define IDC_CHANNMEAN                   5316
#define IDC_CHANNSTD                    5317
#define IDC_AMPLWINDOW                  5318
#define IDC_NEXTCHANNEL                 5319
#define IDC_EXCLCHANNEL                 5320
#define IDC_EXCLCHANNLIST               5321
#define IDC_HELPSTRING                  5322
#define IDC_TRIGGCODE                   5323
#define IDC_TRIGGPOS                    5324
#define IDC_TOEXCLUDE                   5325
#define IDC_CHANNELZOOM                 5326
#define IDC_ACCCOND                     5327
#define IDC_RESTORECURSOR               5328
#define IDC_PROGRESS                    5329
#define IDC_UNDOLAST                    5331
#define IDC_REDOLAST                    5332
#define IDC_UNDOALL                     5333
#define IDC_REDOALL                     5334
#define IDC_RESTARTCURRENT              5335
#define IDC_TIMEINTERVAL                5401
#define IDC_TIMEMIN                     5402
#define IDC_TIMEMAX                     5403
#define IDC_CHANNELS                    5404
#define IDC_TRIGGERSTOKEEP              5405
#define IDC_TRIGGERSTOKEEPLIST          5406
#define IDC_MEAN                        5407
#define IDC_AVEREF                      5408
#define IDC_EXPMARKERS                  5409
#define IDC_CURRENTFILTERS              5410
#define IDC_CURRENTREF                  5411
#define IDC_NOREF                       5412
#define IDC_OPENAUTO                    5413
#define IDC_NOFILTERS                   5414
#define IDC_PROCESSCURRENT              5415
#define IDC_PROCESSBATCH                5416
#define IDC_TOENDOFFILE                 5421
#define IDC_RESCALE_NONE                5422
#define IDC_RESCALE_CSTE                5423
#define IDC_RESCALE_VALUE               5424
#define IDC_RESCALE_GFP                 5425
#define IDC_OTHERREF                    5426
#define IDC_REFLIST                     5427
#define IDC_OTHERFILTERS                5428
#define IDC_USEXYZDOC                   5429
#define IDC_XYZDOCFILE                  5430
#define IDC_BROWSEXYZDOC                5431
#define IDC_INFIXFILENAME               5432
#define IDC_BASELINECORREOF             5434
#define IDC_DOWNSAMPLE                  5435
#define IDC_DOWNSAMPLERATIO             5436
#define IDC_TRACKS                      5437
#define IDC_ROIS                        5438
#define IDC_ROISFILE                    5439
#define IDC_BROWSEROISFILE              5440
#define IDC_OUTPUT1FILE                 5441
#define IDC_TRIGGERSTOEXCLUDE           5442
#define IDC_TRIGGERSTOEXCLUDELIST       5443
#define IDC_ADDCHANNELS                 5444
#define IDC_MINCLUSTERS                 5500
#define IDC_MAXCLUSTERS                 5501
#define IDC_RANDOMTRIALS                5502
#define IDC_CONVERGENCE                 5503
#define IDC_THRESHOLDFACTOR             5505
#define IDC_SMOOTHING                   5506
#define IDC_WINDOWSIZE                  5507
#define IDC_STRENGTH                    5508
#define IDC_BASEFILENAME                5509
#define IDC_BROWSEBASEFILENAME          5510
#define IDC_UPDIRECTORY                 5511
#define IDC_REJECTSMALL                 5512
#define IDC_REJECTSIZE                  5513
#define IDC_ADDEPOCH                    5514
#define IDC_REMOVEEPOCH                 5515
#define IDC_EPOCHFROM                   5516
#define IDC_EPOCHTO                     5517
#define IDC_EPOCHMAPS                   5518
#define IDC_KMEANS                      5519
#define IDC_AAHC                        5520
#define IDC_TAAHC                       5521
#define IDC_SIMPLERFASTER               5522
#define IDC_WRITESEG                    5523
#define IDC_WRITEMAPS                   5524
#define IDC_WRITESYNTH                  5525
#define IDC_SEQUENTIALIZE               5526
#define IDC_MERGECORR                   5527
#define IDC_MERGECORRTHRESH             5528
#define IDC_MERGECORRSMART              5529
#define IDC_MERGECORRSMARTTHRESH        5530
#define IDC_NOTEMPORALPROCESSING        5532
#define IDC_LNORM                       5533
#define IDC_CLIPCORRELATION             5534
#define IDC_MINCORRELATION              5535
#define IDC_ALLTFS                      5536
#define IDC_PRESETSPARAMS               5539
#define IDC_WRITECLUSTERS               5540
#define IDC_INCLUDEFILENAME             5541
#define IDC_FORCESINGLEFILES            5543
#define IDC_BESTTODIR                   5544
#define IDC_PRESETSFILES                5545
#define IDC_FROMCHARS                   5546
#define IDC_TOCHARS                     5547
#define IDC_DELINDIVDIRS                5548
#define IDC_CENTROIDAVG                 5550
#define IDC_CENTROIDWEIGHTAVG           5551
#define IDC_CENTROIDMEDOID              5552
#define IDC_CENTROIDEIGENVECTOR         5553
#define IDC_CENTROIDMEDIAN              5554
#define IDC_TIMEZSCORE                  5557
#define IDC_NOEPOCHS                    5562
#define IDC_MANUALEPOCHS                5563
#define IDC_AUTOEPOCHS                  5564
#define IDC_AUTOEPOCHSSIZE              5565
#define IDC_DUALDATASET                 5566
#define IDC_RESAMPLINGEPOCHS            5567
#define IDC_NUMRESAMPLINGEPOCHS         5568
#define IDC_RESAMPLINGEPOCHSSIZE        5569
#define IDC_RESAMPLINGCOVERAGE          5570
#define IDC_BROWSEISFILE                5580
#define IDC_ISFILE                      5581
#define IDC_ENVELOPEDURATION            5583
#define IDC_ONLYGFPPEAKS                5584
#define IDC_GFPPEAKSAUTO                5585
#define IDC_GFPPEAKSLIST                5586
#define IDC_SKIPBADEPOCHS               5587
#define IDC_SKIPBADEPOCHSAUTO           5588
#define IDC_SKIPBADEPOCHSLIST           5589
#define IDC_ANALYZEMARKERS              5590
#define IDC_SKIPMARKERS                 5591
#define IDC_LSFILENAME                  5600
#define IDC_BROWSELSFILE                5601
#define IDC_WRITESEGFILES               5602
#define IDC_IGNOREPOLARITY              5603
#define IDC_FITSINGLESEG                5604
#define IDC_FONSET                      5605
#define IDC_LOFFSET                     5606
#define IDC_NUMTF                       5607
#define IDC_GEV                         5608
#define IDC_BEV                         5609
#define IDC_TFBEV                       5610
#define IDC_GFPTFBEV                    5611
#define IDC_BCORR                       5612
#define IDC_TFBCORR                     5613
#define IDC_GFPTFBCORR                  5614
#define IDC_MEANCORR                    5615
#define IDC_MEANGFP                     5616
#define IDC_MAXGFP                      5617
#define IDC_TFMAXGFP                    5618
#define IDC_TFCENTROID                  5619
#define IDC_MEANDURATION                5620
#define IDC_TIMECOVERAGE                5621
#define IDC_SEGFREQUENCY                5622
#define IDC_SEGDENSITY                  5623
#define IDC_SHORTVARIABLENAMES          5624
#define IDC_ALLON                       5625
#define IDC_ALLOFF                      5626
#define IDC_NUMWITHINSUBJECTS           5627
#define IDC_MAXWITHINSUBJECTS           5628
#define IDC_WRITECORRFILES              5629
#define IDC_LINESASSAMPLES              5630
#define IDC_COLUMNSASFACTORS            5631
#define IDC_SEPARATEGROUPS              5632
#define IDC_SEPARATEVARIABLES           5633
#define IDC_WRITESEGFREQ                5634
#define IDC_DELETEPREPROCFILES          5635
#define IDC_MARKOVNONE                  5635
#define IDC_MARKOVTF                    5636
#define IDC_MARKOVSEGMENT               5637
#define IDC_MARKOVNUMTRANSITIONS        5638
#define IDC_WRITESTATDURATIONS          5639
#define IDC_CORRELATIONCENTROID         5640
#define IDC_CORRELATIONCLOUD            5641
#define IDC_CORRELATIONSUBJECT          5642
#define IDC_FROMXYZ                     5701
#define IDC_SAMEXYZ                     5702
#define IDC_ANOTHERXYZ                  5703
#define IDC_TOXYZ                       5704
#define IDC_BROWSEFROMXYZ               5705
#define IDC_BROWSETOXYZ                 5706
#define IDC_REMOVINGELEC                5707
#define IDC_FROMTOP                     5710
#define IDC_FROMFRONT                   5711
#define IDC_FROMREAR                    5712
#define IDC_FROMLEFT                    5713
#define IDC_FROMRIGHT                   5714
#define IDC_TOTOP                       5715
#define IDC_TOFRONT                     5716
#define IDC_TOREAR                      5717
#define IDC_TOLEFT                      5718
#define IDC_TORIGHT                     5719
#define IDC_SURFACESPLINE               5720
#define IDC_SPHERICALSPLINE             5721
#define IDC_3DSPLINE                    5722
#define IDC_SPLINEDEGREE                5728
#define IDC_COPYFROMLANDMARKS           5730
#define IDC_COPYTOLANDMARKS             5731
#define IDC_FROMPREDEFLANDMARKS         5732
#define IDC_TOPREDEFLANDMARKS           5733
#define IDC_CLEANUP                     5734
#define IDC_CDSPHERICAL                 5735
#define IDC_FROMDESCRIPTION             5736
#define IDC_TODESCRIPTION               5737
#define IDC_PARAMETERSOK                5738
#define IDC_STABMIN                     5801
#define IDC_STABMAX                     5802
#define IDC_GAP                         5803
#define IDC_THRESHOLD                   5804
#define IDC_SCANSTABILITY               5805
#define IDC_SCANTHRESHOLD               5806
#define IDC_THRESHOLDSTRICT             5809
#define IDC_THRESHOLDSMARTSLOPE         5810
#define IDC_SCANTEMPLATE                5813
#define IDC_SCANTEMPLATEFILE            5814
#define IDC_SCANTEMPLATETHRESHOLD       5815
#define IDC_SCANEXTREMA                 5816
#define IDC_SCANMIN                     5817
#define IDC_SCANMAX                     5818
#define IDC_ONEMARKERPERTRACK           5819
#define IDC_MERGEMARKERS                5820
#define IDC_MERGEMARKERSRANGE           5821
#define IDC_PREFIXMARKER                5822
#define IDC_PREFIXMARKERSTRING          5823
#define IDC_TRACKNAME                   5824
#define IDC_NOVALUE                     5825
#define IDC_TRACKVALUE                  5826
#define IDC_TRACKRELATIVEINDEX          5827
#define IDC_MERGEDCOUNT                 5828
#define IDC_NUMBLOCKS                   5900
#define IDC_BLOCKSIZE                   5901
#define IDC_SAMPLINGFREQUENCY           5902
#define IDC_FREQMIN                     5903
#define IDC_FREQMAX                     5904
#define IDC_FREQSTEP                    5905
#define IDC_SAVEFREQMIN                 5906
#define IDC_SAVEFREQMAX                 5907
#define IDC_SIMPLEFFT                   5908
#define IDC_POWERMAPS                   5909
#define IDC_FFTAPPROXIMATION            5910
#define IDC_WRITETYPE                   5911
#define IDC_CLIPPEDTIMEMAX              5915
#define IDC_SEQUENCE                    5916
#define IDC_WINDOWOVERLAP0              5917
#define IDC_WINDOWOVERLAP25             5918
#define IDC_WINDOWOVERLAP50             5919
#define IDC_WINDOWOVERLAP75             5920
#define IDC_WINDOWOVERLAPMAX            5921
#define IDC_WINDOWINGNONE               5922
#define IDC_WINDOWINGHANNING            5923
#define IDC_WINDOWSINTERVAL             5924
#define IDC_STRANSFORM                  5925
#define IDC_SAVEFREQSTEP                5926
#define IDC_SAVEINTERVAL                5927
#define IDC_SAVELOGINTERVAL             5928
#define IDC_SAVEBANDS                   5929
#define IDC_SAVEBANDSVALUE              5930
#define IDC_CREATESUBDIR                5931
#define IDC_WINDOWINGHANNINGBORDER      5933
#define IDC_DECADESTEP                  5934
#define IDC_OPTIMALDOWNSAMPLING         5935
#define IDC_SPLITBYSPECTRUM             5936
#define IDC_SPLITBYELECTRODE            5937
#define IDC_SPLITBYFREQUENCY            5938
#define IDC_FFTNORMALIZATION            5939
#define IDC_BASELINE                    6001
#define IDC_BUTTERWORTHHIGH             6002
#define IDC_BUTTERWORTHHIGHVALUE        6003
#define IDC_BUTTERWORTHLOW              6004
#define IDC_BUTTERWORTHLOWVALUE         6005
#define IDC_CAUSAL                      6006
#define IDC_NONCAUSAL                   6007
#define IDC_NOTCH                       6008
#define IDC_NOTCHVALUES                 6009
#define IDC_SPATIALFILTER               6010
#define IDC_RANKING                     6011
#define IDC_RECTIFICATION               6012
#define IDC_RECTIFICATIONABS            6013
#define IDC_RECTIFICATIONPOWER          6014
#define IDC_ENVELOPE                    6015
#define IDC_ENVELOPEWIDTH               6016
#define IDC_ENVELOPEFREQ                6017
#define IDC_THRESHOLDABOVE              6018
#define IDC_THRESHOLDABOVEVALUE         6019
#define IDC_THRESHOLDBELOW              6020
#define IDC_THRESHOLDBELOWVALUE         6021
#define IDC_AUXSAMPLINGFREQUENCY        6022
#define IDC_FILTERSON                   6023
#define IDC_FILTERSOFF                  6024
#define IDC_FILTERAUXS                  6025
#define IDC_FILTERORDERHIGH             6026
#define IDC_FILTERORDERLOW              6027
#define IDC_NOTCHAUTOHARMONICS          6028
#define IDC_TFSEQUENTIAL                6102
#define IDC_TFAVERAGE                   6103
#define IDC_ADDGROUP                    6104
#define IDC_USELASTGROUP                6105
#define IDC_NUMGROUPS                   6106
#define IDC_GROUPSSUMMARY               6107
#define IDC_THRESHOLDINGPVALUES         6108
#define IDC_THRESHOLDINGPVALUESVALUE    6109
#define IDC_SAMPLESNFILES               6110
#define IDC_SAMPLES1FILE                6111
#define IDC_SAMPLESCSVFILE              6112
#define IDC_RESCALE_GFP_1TF             6118
#define IDC_MINSIGNIFICANTDURATIONVALUE 6126
#define IDC_NUMBEROFRANDOMIZATIONS      6129
#define IDC_RESCALE_GFP_PAIRED          6130
#define IDC_CHECKMISSINGVALUES          6131
#define IDC_CHECKMISSINGVALUESVALUE     6132
#define IDC_SPATIALCONSISTENCY          6133
#define IDC_MOREOUTPUTS                 6134
#define IDC_SIGNEDDATA                  6135
#define IDC_POSITIVEDATA                6136
#define IDC_VECTORDATA                  6137
#define IDC_ACCOUNTPOLARITY             6138
#define IDC_PRESETS                     6139
#define IDC_OUTPUTP                     6140
#define IDC_OUTPUT1MINUSP               6141
#define IDC_OUTPUTMINUSLOGP             6142
#define IDC_PRESETSTIME                 6143
#define IDC_MULTIPLETESTSCORRECTION     6144
#define IDC_FDRCORRECTION               6145
#define IDC_FDRCORRECTIONVALUE          6146
#define IDC_BONFERRONCORRECTION         6147
#define IDC_PRESETSCORRECTION           6148
#define IDC_MINSIGNIFICANTDURATION      6149
#define IDC_UNPAIREDTEST                6150
#define IDC_PAIREDTEST                  6151
#define IDC_TTEST                       6152
#define IDC_RANDOMIZATION               6153
#define IDC_TANOVA                      6154
#define IDC_TRACKSFILE                  6200
#define IDC_BROWSETRACKSFILE            6201
#define IDC_XYZFILE                     6202
#define IDC_BROWSEXYZFILE               6203
#define IDC_SPFILE                      6204
#define IDC_BROWSESPFILE                6205
#define IDC_MRIFILE                     6206
#define IDC_BROWSEMRIFILE               6207
#define IDC_GETSELECTION                6208
#define IDC_ADDSELECTION                6209
#define IDC_REMOVESELECTION             6210
#define IDC_SELECTION                   6211
#define IDC_ROINAME                     6212
#define IDC_NUMROIS                     6213
#define IDC_ROISSUMMARY                 6214
#define IDC_MRISPTOROIS                 6215
#define IDC_GENERATEROISFILE            6216
#define IDC_BROWSEGENERATEROISFILE      6217
#define IDC_MESSAGEINTERACTIVE          6218
#define IDC_TALAIRACHTOROIS             6219
#define IDC_PROCESSINTERACTIVE          6220
#define IDC_PROCESSAUTOMATIC            6221
#define IDC_USEMRIFILE                  6222
#define IDC_ROISLABELSFILE              6223
#define IDC_BROWSEROISLABELSFILE        6224
#define IDC_AALTOROIS                   6225
#define IDC_INPUTSPFILE                 6232
#define IDC_BROWSEINPUTSPFILE           6233
#define IDC_OUTPUTSPFILE                6234
#define IDC_BROWSEOUTPUTSPFILE          6235
#define IDC_GREYFAT                     6247
#define IDC_GREYALL                     6248
#define IDC_EXPRESSION                  6300
#define IDC_COMPOUNDFILENAMES           6301
#define IDC_GENERICFILENAMES            6302
#define IDC_REGULARIZATION              6303
#define IDC_MRIPRESETS                  6400
#define IDC_MRIFILE1                    6401
#define IDC_MRIFILE2                    6402
#define IDC_MRIFILE3                    6403
#define IDC_BROWSEMRIFILE1              6404
#define IDC_BROWSEMRIFILE2              6405
#define IDC_BROWSEMRIFILE3              6406
#define IDC_BIASFIELD                   6407
#define IDC_SMOOTHMRI                   6408
#define IDC_REORIENTMRIS                6409
#define IDC_SETSAGITTALPLANEMRI         6410
#define IDC_SETEQUATORPLANEMRI          6411
#define IDC_XYZPRESETS                  6420
#define IDC_SPPRESETS                   6430
#define IDC_NUMSOLPOINTS                6431
#define IDC_LEADFIELDPRESETS            6440
#define IDC_THICKNESSFROMMRI            6441
#define IDC_THICKNESSFROMTISSUES        6442
#define IDC_TISSUESFILE                 6443
#define IDC_BROWSETISSUESFILE           6444
#define IDC_LEAFIELDTARGETAGE           6445
#define IDC_SKULLCONDUCTIVITY           6446
#define IDC_ADJUSTSKULLMEANTHICKNESS    6447
#define IDC_SKULLMEANTHICKNESS          6448
#define IDC_LEADFIELDFILE               6449
#define IDC_BROWSELEADFIELDFILE         6450
#define IDC_INVERSEMN                   6460
#define IDC_INVERSEWMN                  6461
#define IDC_INVERSELORETA               6462
#define IDC_INVERSELAURA                6463
#define IDC_INVERSESLORETA              6464
#define IDC_INVERSEELORETA              6465
#define IDC_INVERSEDALE                 6466
#define IDC_INVERSEALL                  6467
#define IDC_INTERACTIVE                 6480
#define IDC_AUTOMATIC                   6481
#define IDC_TOPREVDIALOG                7000
#define IDC_TONEXTDIALOG                7001
#define IDC_FILETYPES                   7002
#define IDC_FILETYPE_TXT                7010
#define IDC_FILETYPE_EP                 7011
#define IDC_FILETYPE_EPH                7012
#define IDC_FILETYPE_SEF                7013
#define IDC_FILETYPE_BV                 7014
#define IDC_FILETYPE_EDF                7015
#define IDC_FILETYPE_RIS                7016
#define IDC_FILETYPE_FREQ               7017
#define IDC_FILETYPE_SPECTRUM           7018
#define IDC_REGAUTO                     7200
#define IDC_REGFIXED                    7201
#define IDC_REGFIXEDEDIT                7202
#define IDC_RISPRESETS                  7203
#define IDC_TRACKSOUTPUT                7205
#define IDC_VOLUMESOUTPUT               7206
#define IDC_GREYMASKFILE                7207
#define IDC_BROWSEGREYMASKFILE          7208
#define IDC_STEPTF                      7209
#define IDC_ALLSUBJECTSPERGROUP         7210
#define IDC_ALLCONDITIONSPERGROUP       7211
#define IDC_SAVEINDIVIDUALFILES         7212
#define IDC_SAVEZSCOREFACTORS           7213
#define IDC_COMPUTEGROUPSAVERAGES       7214
#define IDC_COMPUTEGROUPSCENTROIDS      7215
#define IDC_COMPUTEZSCORE               7216
#define IDC_LOADZSCOREFILE              7217
#define IDC_GROUPPRESETS                7218
#define IDC_SAVEEPOCHFILES              7219
#define IDC_ENVELOPELOWFREQ             7220
#define IDC_NUMSUBJECTS                 7221
#define IDC_NUMCONDITIONS               7222
#define IDC_RANKRIS                     7223
#define IDC_THRESHOLDRIS                7224
#define IDC_MRIPREPROCPRESETS           7300
#define IDC_ISOTROPIC                   7301
#define IDC_RESIZING                    7302
#define IDC_RESIZEDIM                   7303
#define IDC_RESIZEVOXEL                 7304
#define IDC_RESIZEDIMVALUE              7305
#define IDC_RESIZEVOXELVALUE            7306
#define IDC_REORIENTING                 7307
#define IDC_REORIENTINGRAS              7308
#define IDC_REORIENTINGOTHER            7309
#define IDC_REORIENTINGX                7310
#define IDC_REORIENTINGY                7311
#define IDC_REORIENTINGZ                7312
#define IDC_REALIGNING                  7313
#define IDC_ALIGNSAGITTAL               7314
#define IDC_SETTINGORIGIN               7315
#define IDC_SETORIGINIFNOTSET           7316
#define IDC_SETORIGNALWAYS              7317
#define IDC_ORIGINCENTER                7318
#define IDC_ORIGINFIXED                 7319
#define IDC_ORIGINX                     7320
#define IDC_ORIGINY                     7321
#define IDC_ORIGINZ                     7322
#define IDC_MRISKULLSTRIPPINGPRESETS    7323
#define IDC_BFC                         7324
#define IDC_COREGISTERING               7325
#define IDC_BRAINFILE                   7326
#define IDC_BROWSEBRAINFILE             7327
#define IDC_RESIZERATIO                 7328
#define IDC_RESIZERATIOVALUE            7329
#define IDC_ALIGNTRANSVERSE             7330
#define IDC_ORIGINMNI                   7331
#define IDC_SIZETRANSFORMED             7334
#define IDC_SIZEOPTIMAL                 7335
#define IDC_SIZEUSER                    7336
#define IDC_SIZEUSERX                   7337
#define IDC_SIZEUSERY                   7338
#define IDC_SIZEUSERZ                   7339
#define IDC_FULLHEADCLEANUP             7340
#define IDC_MRITYPEPRESETS              7350
#define IDC_GREYMASKTYPEPRESETS         7351
#define IDC_SPNUMBER                    7352
#define IDC_SPNUMBEREDIT                7353
#define IDC_SPRESOLUTION                7354
#define IDC_SPRESOLUTIONEDIT            7355
#define IDC_SPFROMBRAIN                 7356
#define IDC_SPFROMSP                    7357
#define IDC_SPTYPEPRESETS               7358
#define IDC_RISTOVOLPRESETS             7400
#define IDC_TIMEALL                     7401
#define IDC_UNSIGNEDBYTE                7402
#define IDC_FLOAT                       7403
#define IDC_INTERPOLATIONPRESETS        7404
#define IDC_SCALEGLOBALPLUS             7500
#define IDC_SCALEGLOBALMINUS            7501
#define IDC_SCALEXPLUS                  7502
#define IDC_SCALEXMINUS                 7503
#define IDC_SCALEYPLUS                  7504
#define IDC_SCALEYMINUS                 7505
#define IDC_SCALEZPLUS                  7506
#define IDC_SCALEZMINUS                 7507
#define IDC_TRANSLATEXPLUS              7508
#define IDC_TRANSLATEXMINUS             7509
#define IDC_TRANSLATEYPLUS              7510
#define IDC_TRANSLATEYMINUS             7511
#define IDC_TRANSLATEZPLUS              7512
#define IDC_TRANSLATEZMINUS             7513
#define IDC_ROTATEXPLUS                 7514
#define IDC_ROTATEXMINUS                7515
#define IDC_ROTATEYPLUS                 7516
#define IDC_ROTATEYMINUS                7517
#define IDC_ROTATEZPLUS                 7518
#define IDC_ROTATEZMINUS                7519
#define IDC_GLUE                        7520
#define IDC_RESETTRANSFORM              7521
#define IDC_SAVINGALTELEC               7522
#define IDS_ERROR_MEMALLOC              10004
#define IDC_OWLNEXTBUILDDATE            20022
#define IDD_ABOUT                       22000
#define IDC_VERSION                     22001
#define IDC_BRANCH                      22002
#define IDC_COPYRIGHT                   22003
#define IDC_BUILD                       22004
#define IDC_BUILDDATE                   22005
#define IDC_APPNAME                     22006
#define IDC_OPTIMIZATIONS               22007
#define IDC_OGLVERSION                  22010
#define IDC_OGLVENDOR                   22011
#define IDC_OGLRENDERER                 22012
#define IDC_OGLEXTENSIONS               22013
#define IDC_OGLPROP1                    22014
#define IDC_OGLPROP2                    22015
#define IDC_GLSLVERSION                 22016
#define IDC_OGLRENDERER2                22019
#define IDC_OWLNEXTVERSION              22020
#define IDC_OWLNEXTBUILD                22021
#define IDC_OWLNEXTPRODUCTNAME          22023
#define IDC_OWLNEXTCOPYRIGHT            22024
#define IDC_OWLNEXTCOMPANYNAME          22025
#define IDC_OWLNEXTURL                  22026
#define IDC_HELPCURSOR                  24000
#define IDC_SYNCVIEWS                   24001
#define IDC_ADDTOGROUP                  24002
#define IDC_LINKVIEW                    24003
#define IDC_MAGNIFY                     24004
#define IDC_OPERATION                   24005
#define CM_EXIT                         24310
#define CM_EDITUNDO                     24321
#define CM_EDITCUT                      24322
#define CM_EDITCOPY                     24323
#define CM_EDITPASTE                    24324
#define CM_EDITDELETE                   24325
#define CM_EDITCLEAR                    24326
#define CM_EDITADD                      24327
#define CM_EDITEDIT                     24328
#define CM_EDITREDO                     24329
#define CM_FILENEW                      24331
#define CM_MDIFILENEW                   24331
#define CM_FILEOPEN                     24332
#define CM_MDIFILEOPEN                  24332
#define CM_FILESAVE                     24333
#define CM_FILESAVEAS                   24334
#define CM_FILEREVERT                   24335
#define CM_FILEPAGESETUP                24336
#define CM_FILEPRINT                    24337
#define CM_FILEPRINTERSETUP             24338
#define CM_FILECLOSE                    24339
#define CM_FILEPRINTPREVIEW             24340
#define CM_VIEWCREATE                   24341
#define CM_EDITFIND                     24351
#define CM_EDITREPLACE                  24352
#define CM_EDITFINDNEXT                 24353
#define CM_CASCADECHILDREN              24361
#define CM_TILECHILDREN                 24362
#define CM_TILECHILDRENHORIZ            24363
#define CM_ARRANGEICONS                 24364
#define CM_CLOSECHILDREN                24365
#define CM_CREATECHILD                  24366
#define CM_HELPCONTENTS                 24371
#define CM_HELPUSING                    24372
#define CM_HELPABOUT                    24373
#define CM_HELPCARTOOLCOMMUNITY         24374
#define CM_HELPWEBUSERSGUIDE            24375
#define CM_HELPWEBREFERENCEGUIDE        24376
#define CM_HELPWEBRELEASES              24378
#define CM_HELPAUTOUPDATE               24379
#define CM_HELPWEBCIBM                  24380
#define CM_HELPCARTOOLGITHUB            24381
#define IDI_OWLAPP                      32000
#define IDW_MDICLIENT                   32000
#define IDB_HSLIDERTHUMB                32000
#define IDI_OWLAPPSM                    32001
#define IDW_FIRSTMDICHILD               32001
#define IDB_VSLIDERTHUMB                32001
#define IDW_STATUSBAR                   32040
#define IDW_TOOLBAR                     32041
#define IDM_DOCMANAGERFILE              32401
#define IDS_DOCMANAGERFILE              32500
#define IDS_DOCLIST                     32501
#define IDS_VIEWLIST                    32502
#define IDS_UNTITLED                    32503
#define IDS_UNABLEOPEN                  32504
#define IDS_UNABLECLOSE                 32505
#define IDS_READERROR                   32506
#define IDS_WRITEERROR                  32507
#define IDS_DOCCHANGED                  32508
#define IDS_NOTCHANGED                  32509
#define IDS_NODOCMANAGER                32510
#define IDS_NOMEMORYFORVIEW             32511
#define IDS_DUPLICATEDOC                32512
#define IDS_VALPXPCONFORM               32520
#define IDS_VALINVALIDCHAR              32521
#define IDS_VALNOTINRANGE               32522
#define IDS_VALNOTINLIST                32523
#define IDS_MODES                       32530
#define IDS_MODESOFF                    32531
#define IDS_CANNOTFIND                  32540
#define IDM_EDITSEARCH                  32541
#define IDA_EDITSEARCH                  32542
#define IDS_UNTITLEDFILE                32550
#define IDM_EDITFILE                    32550
#define IDA_EDITFILE                    32550
#define IDS_UNABLEREAD                  32551
#define IDS_UNABLEWRITE                 32552
#define IDS_FILECHANGED                 32553
#define IDS_FILEFILTER                  32554
#define IDS_RICHEDITFILTER              32555
#define IDM_EDITVIEW                    32581
#define IDM_LISTVIEW                    32582
#define IDS_LISTNUM                     32584
#define IDS_PRNON                       32590
#define IDS_PRNERRORTEMPLATE            32591
#define IDS_PRNOUTOFMEMORY              32592
#define IDS_PRNOUTOFDISK                32593
#define IDS_PRNCANCEL                   32594
#define IDS_PRNMGRABORT                 32595
#define IDS_PRNGENERROR                 32596
#define IDS_PRNERRORCAPTION             32597
#define IDS_INVALIDCLIENTWINDOW         32707
#define IDS_INVALIDCHILDWINDOW          32708
#define IDS_INVALIDWINDOW               32709
#define IDS_INVALIDDIBHANDLE            32732
#define IDS_GDIDESTROYFAIL              32733
#define IDS_GDIDELETEFAIL               32734
#define IDS_GDIFILEREADFAIL             32735
#define IDS_GDIRESLOADFAIL              32736
#define IDS_GDICREATEFAIL               32737
#define IDS_GDIALLOCFAIL                32738
#define IDS_GDIFAILURE                  32739
#define IDS_LAYOUTBADRELWIN             32740
#define IDS_LAYOUTINCOMPLETE            32741
#define IDS_PRINTERERROR                32742
#define IDS_VALIDATORSYNTAX             32743
#define IDS_MENUFAILURE                 32744
#define IDS_CHILDCREATEFAIL             32745
#define IDS_WINDOWEXECUTEFAIL           32746
#define IDS_WINDOWCREATEFAIL            32747
#define IDS_CHILDREGISTERFAIL           32748
#define IDS_CLASSREGISTERFAIL           32749
#define IDS_VBXLIBRARYFAIL              32758
#define IDS_INVALIDMAINWINDOW           32759
#define IDS_INVALIDMODULE               32760
#define IDS_OUTOFMEMORY                 32761
#define IDS_NOAPP                       32762
#define IDS_UNKNOWNERROR                32763
#define IDS_UNHANDLEDXMSG               32764
#define IDS_OKTORESUME                  32765
#define IDS_OWLEXCEPTION                32766
#define IDS_UNKNOWNEXCEPTION            32767

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
